# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


autoload -Uz promptinit
promptinit

# User specific aliases and functions

# Tmux {{{
# Makes creating a new tmux session (with a specific name) easier
function tmuxopen() {
  tmux attach -t $1
}

# Makes creating a new tmux session (with a specific name) easier
function tmuxnew() {
  tmux new -s $1
}

# Makes deleting a tmux session easier
function tmuxkill() {
  tmux kill-session -t $1
}
# }}}

source ~/.toolsconfig/alias

fpath=(~/appslnx/zsh-completions/src $fpath)

#. /home/j/appslnx/erlang/19.0/activate


source ~/.toolsconfig/env-variables

#. /home/j/appslnx/opt/erlang/19.0/activate


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


bindkey -v
bindkey '^R' history-incremental-search-backward

. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash
